# Generated by Django 5.0.3 on 2024-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trin', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('attendees', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room', models.ManyToManyField(related_name='bookings', to='room.room')),
            ],
        ),
    ]
